### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by astier** [ShibiHe/Model-Free-Episodic-Control#4]
Hi. A year ago or so I forked your model-free-episodic-control repository. I refactored, deleted and added a lot of code. I published it on my github-account under the MIT-license and mention you as the original author. At that time I never thought about the fact that you do not include a license. Now I ask you to add a license to your project (preferably MIT or GPL v3) not just for me but also for all other people who may would like to use your code but are afraid because your have no license. Thank you!

**Comment by ShibiHe** [comment]
Thanks Astier!

**Comment by ShibiHe** [comment]
Thanks for mentioning me in your readme. Will also mention you in my readme
